### PR TITLE
use GitHub Actions, nbval to test notebooks and clean up current notebooks.

### PR DESCRIPTION
**Pull request by MridulS**

### CODE REVIEW

**Comment by MridulS** [comment]
@rossbar @jarrodmillman any idea why Github Actions aren't triggered by this?

**Comment by jarrodmillman** [comment]
@MridulS I just enabled actions in the settings for this repo.  Try pushing again.

**Comment by jarrodmillman** [comment]
To get pygraphviz installed, you may want to copy this recipe:
https://github.com/networkx/networkx/pull/4320/files#diff-4cab9ea3ef9576c30aa9b733cc577e29915b1c2d1c05c6efa50ed0c19fc4b120

For instance, I don't think ubuntu-latest will work; but there are a couple other things you need to do as well.

**Comment by MridulS** [comment]
Currently testing notebook using nbval-lax (just tests if every cell executes)

**Pull request merged**
